###############
# Base Schema
###############

type Subscriber {
  id: Int!
  email: String!
  firstname: String
  lastname: String
  subscriptions: Subscriptions!
  token: String
  createTime: String
}

extend type Query {
  subscribers(sort: SubscriberSortOptions): [Subscriber]
  subscriber(id: Int!): Subscriber
}

extend type Mutation {
  createSubscriber(subscriber: SubscriberInput!): Subscriber
  updateSubscriber(id: Int!, subscriber: SubscriberInput!): Subscriber
  deleteSubscriber(id: Int!): Subscriber
}

###############
# Helpers
###############

input SubscriberSortOptions {
  field: SubscriberSortField
  order: OrderOption
}

enum SubscriberSortField {
  id
  createTime
}

input SubscriberInput {
  email: String!
  firstname: String
  lastname: String
  subscriptions: SubscriptionsInput
}

type Subscriptions {
  Reveries: Boolean
  Diary: Boolean
}

input SubscriptionsInput {
  Reveries: Boolean!
  Diary: Boolean!
}
