###############
# Base Schema
###############

type Post {
  id: Int
  title: String!
  type: PostType!
  datePublished: String
  content: String
  image: String
  slug: String
  excerpt: String
  status: PostStatus
  createTime: String
  domainId: Int
  domainType: PostType
}

type Query {
  getAllPosts(limit: Int, sort: PostOrder, type: PostType): [Post]
  getSinglePost(id: Int!): Post
}

type Mutation {
  createPost(post: PostInput, isPublish: Boolean): Post
  updatePost(
    id: Int!
    post: PostInput!
    isPublish: Boolean
    imageHasChanged: Boolean
  ): Post
  deletePost(id: Int!): Post
}

###############
# Helpers
###############

enum PostType {
  Epistle
  Reverie
  Poem
  Page
  Musing
}

enum PostField {
  id
  title
  type
  datePublished
  status
  createTime
}

enum PostStatus {
  DRAFT
  PRIVATE
  PUBLISHED
}

enum Order {
  ASC
  DESC
  RANDOM
}

input PostInput {
  # No slug
  title: String!
  type: PostType!
  datePublished: String
  content: String
  image: String
  excerpt: String
  status: PostStatus
  domainId: Int
  domainType: PostType
}

input PostOrder {
  field: PostField
  order: Order
}