
type Post {
  id: Int
  title: String!
  datePublished: String
  content: String
  image: String
  slug: String
  excerpt: String
  type: PostType
  status: ArticleStatus
  createTime: String
}

enum PostType {
  Epistle
  Reverie
  Poem
  Page
}

enum ArticleStatus {
  DRAFT
  PRIVATE
  PUBLISHED
}

input PostInput {
  title: String!
  datePublished: String
  content: String
  image: String
  slug: String
  excerpt: String
  status: ArticleStatus
  type: PostType
}

type Query {
  getAllPosts(limit: Int, random: Boolean, type: PostType): [Post],
  getSinglePost(id: Int!): Post
}

type Mutation {
  createPost(post: PostInput): Post
  updatePost(id: Int!, post: PostInput): Post
  deletePost(id: Int!): Post
}