default:
  image: node:18.17.1-slim
  cache:
    - key:
        files:
          - bun.lockb
      paths:
        - node_modules
        - .next/cache
    - key:
        files:
          - tsconfig.json
      paths:
        - .tsbuildinfo
    - key:
        files:
          - .eslintrc.js
      paths:
        - .eslintcache

.install_dependencies:
  - npm i -g bun@1.0.3
  - bun install --frozen-lockfile
  - bun prisma generate

stages:
  - evaluate

inspect:
  stage: evaluate
  before_script: !reference [.install_dependencies]
  script:
    - bun run tsc:ci

build:
  stage: evaluate
  before_script: !reference [.install_dependencies]
  script:
    - bun run build

test:unit:
  stage: evaluate
  before_script: !reference [.install_dependencies]
  script:
    - bun run test:unit

test:e2e:
  stage: evaluate
  before_script: !reference [.install_dependencies]
  script:
    - bun run test
