version: '3.5'

services:
  staging:
    image: zavid_dev
    container_name: zavid_blog_staging
    build:
      context: .
      args:
        WORKDIR: dev.zavid
    environment:
      PORT: 3333
    ports:
      - '3333:3333'
    restart: unless-stopped
    volumes:
      - /var/www/dev.zavid/.next/cache

  production:
    image: zavid
    container_name: zavid_blog_production
    build:
      context: .
      args:
        WORKDIR: zavid
    environment:
      PORT: 4000
    ports:
      - '4000:4000'
    restart: unless-stopped
    volumes:
      - /var/www/dev.zavid/.next/cache

  analytics:
    image: matomo
    container_name: matomo_analytics
    ports:
      - '8500:80'
    volumes:
      - matomo:/var/www/html
