version: '3.5'

services:
  staging:
    image: zavid_dev
    container_name: zavid_blog_staging
    build: .
    environment:
      PORT: 3333
    ports:
      - '3333:3333'
    restart: unless-stopped
    volumes:
      - /var/www/dev.zavid/.next/cache

  production:
    image: zavid
    container_name: zavid_blog_production
    build: .
    environment:
      PORT: 4000
    ports:
      - '4000:4000'
    restart: unless-stopped
    volumes:
      - /var/www/dev.zavid/.next/cache

  analytics:
    image: matomo:4.15.1
    container_name: matomo_analytics
    ports:
      - '8500:80'
    volumes:
      - /var/www/analytics.zavid/matomo:/var/www/html
