version: 2.1

jobs:
  deploy:
    docker:
      - image: kroniak/ssh-client
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "ls"

workflows:
  version: 2
  build-project:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main