version: 2.1

jobs:
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./blog-zavid/docker/deploy.sh"

workflows:
  version: 2
  build-project:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main