version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"

workflows:
  version: 2
  build-project:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main