###############
# Base Schema
###############

type DiaryEntry {
  id: Int!
  date: String
  content: String
  slug: String
  status: DiaryStatus
}

extend type Query {
  diaryEntries(
    sort: DiarySortOptions
    status: DiaryStatusOptions
  ): [DiaryEntry]
  diaryEntry(id: Int!): DiaryEntry
}

extend type Mutation {
  createDiaryEntry(diaryEntry: DiaryInput!, isPublish: Boolean): DiaryEntry
  updateDiaryEntry(
    id: Int!
    diaryEntry: DiaryInput!
    isPublish: Boolean
  ): DiaryEntry
  deleteDiaryEntry(id: Int!): DiaryEntry
}

###############
# Helpers
###############

enum DiaryStatus {
  PRIVATE
  PUBLISHED
}

enum DiarySortField {
  id
  date
  status
}

input DiarySortOptions {
  field: DiarySortField
  order: OrderOption
}

input DiaryStatusOptions {
  include: [DiaryStatus]
  exclude: [DiaryStatus]
}

input DiaryInput {
  content: String
  date: String
  status: DiaryStatus
}
