###############
# Base Schema
###############

type Post {
  id: Int
  title: String!
  type: PostType!
  typeId: Int
  datePublished: String
  content: String
  image: String
  contentImages: [String]
  slug: String
  excerpt: String
  status: PostStatus
  createTime: String
  domainId: Int
  domainTitle: String
  domainType: PostType
  domainSlug: String
}

extend type Query {
  getAllPosts(
    limit: Int
    sort: PostSortOptions
    type: PostTypeOptions
    status: PostStatusOptions
  ): [Post]
  getSinglePost(id: Int!): Post
}

extend type Mutation {
  createPost(post: PostInput, isPublish: Boolean, isTest: Boolean): Post
  updatePost(
    id: Int!
    post: PostInput!
    isPublish: Boolean
    isTest: Boolean
  ): Post
  deletePost(id: Int!): Post
}

###############
# Helpers
###############

enum PostType {
  Epistle
  Reverie
  Poem
  Page
  Musing
}

enum PostSortField {
  id
  title
  type
  datePublished
  status
  createTime
}

enum PostStatus {
  DRAFT
  PRIVATE
  PUBLISHED
}

input PostInput {
  # No slug
  title: String!
  type: PostType!
  typeId: Int!
  datePublished: String
  content: String
  image: ImageState
  contentImages: [ImageState]
  excerpt: String
  status: PostStatus
  domainId: Int
}

input PostSortOptions {
  field: PostSortField
  order: OrderOption
}

input PostTypeOptions {
  include: [PostType]
  exclude: [PostType]
}

input PostStatusOptions {
  include: [PostStatus]
  exclude: [PostStatus]
}

input ImageState {
  source: String
  hasChanged: Boolean
}
