#!/bin/bash

cd code || exit 1

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$BRANCH" == "production" ]]; then
  echo 'Skipping pre-commit hooks for production'
  exit 0
fi

pnpm run eslint --max-warnings 0 || exit 1

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
echo "$FILES" | xargs pnpm run prettier:write --ignore-unknown
echo "$FILES" | xargs git add
echo "$FILES" | xargs git commit -m "Run Prettier"
exit 0
