#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

## Skip if CI
[ -n "$CI" ] && exit 0

## Skip if production branch
if [[ "$(git rev-parse --abbrev-ref HEAD)" == "production" ]]; then
  echo 'Skipping pre-push hooks for production.'
  exit 0
fi

bun run eslint --max-warnings 0 || exit 1
