#!/bin/bash

## Skip if CI
[ -n "$CI" ] && exit 0

## Skip if production branch
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$BRANCH" == "production" ]]; then
  echo 'Skipping pre-push hooks for production.'
  exit 0
fi

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
echo "$FILES" | xargs bun run prettier --write --ignore-unknown
echo "$FILES" | xargs git add
exit 0
