#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

## Skip if CI
[ -n "$CI" ] && exit 0

## Skip if production branch
if [[ "$(git rev-parse --abbrev-ref HEAD)" == "production" ]]; then
  echo 'Skipping pre-push hooks for production.'
  exit 0
fi

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
# echo "$FILES" | xargs ./node_modules/.bin/eslint --ext .ts,.tsx . --cache --fix
echo "$FILES" | xargs ./node_modules/.bin/prettier --write --ignore-unknown
echo "$FILES" | xargs git add
exit 0
