name: 'Ops: Backup Production Database'

on:
  schedule:
    - cron: '0 9 * * 1,4'
  workflow_dispatch:

env:
  APP_KEY_ID: ${{ secrets.APP_KEY_ID }}
  APP_KEY_VALUE: ${{ secrets.APP_KEY_VALUE }}
  BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_DB: ${{ secrets.MYSQL_DB }}

jobs:
  backup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ops/backup
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: ops/backup
          sparse-checkout-cone-mode: false
      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun run start
