name: Deploy ZAVID Blog

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        uses: ./.github/actions/install.yml
      - name: "Run TypeScript checks"
        run: pnpm run tsc:ci
      - name: "Run ESLint"
        run: pnpm run eslint --max-warnings 0