name: Deploy ZAVID Blog

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: "Cache TypeScript build info"
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/code/.tsbuildinfo
          key: ${{ runner.os }}-typescript-${{ hashFiles('**/tsconfig.json') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-typescript-${{ hashFiles('**/tsconfig.json') }}
      - name: "Run TypeScript checks"
        run: pnpm run tsc:ci
        working-directory: code
      - name: "Cache ESLint results"
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/code/.eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/.eslintrc.js') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-eslint-${{ hashFiles('**/.eslintrc.js') }}
      - name: "Run ESLint"
        run: pnpm run eslint --max-warnings 0
        working-directory: code
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: "Cache Next.js build"
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/code/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: "Build project"
        run: pnpm run build
        working-directory: code
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: "Install test browsers"
        run: npx playwright install --with-deps
      - name: "Run e2e tests"
        run: pnpm run test
        working-directory: code
      - name: "Publish test report"
        uses: mikepenz/action-junit-report@v3.7.8
        if: always()
        with:
          report_paths: ${{ github.workspace }}/code/test/results/results.xml