name: Deploy ZAVID Blog

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        uses: ./.github/actions/install
      - name: "Run TypeScript checks"
        run: pnpm run tsc:ci
        working-directory: code
      - name: "Run ESLint"
        run: pnpm run eslint --max-warnings 0
        working-directory: code
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        uses: ./.github/actions/install
      - name: "Build project"
        run: pnpm run build
        working-directory: code
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        uses: ./.github/actions/install
      - name: "Run e2e tests"
        run: pnpm run test
        working-directory: code