name: Deploy ZAVID Blog

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/install.yml
    steps:
      - name: "Run TypeScript checks"
        run: pnpm run tsc:ci
      - name: "Run ESLint"
        run: pnpm run eslint --max-warnings 0