name: Deploy ZAVID Blog

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: "Run TypeScript checks"
        run: pnpm run tsc:ci
        working-directory: code
      - name: "Run ESLint"
        run: pnpm run eslint --max-warnings 0
        working-directory: code
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: "Build project"
        run: pnpm run build
        working-directory: code
      - name: "Cache Next.js build"
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/code/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: "Run e2e tests"
        run: pnpm run test
        working-directory: code
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: ${{ github.workspace }}/code/test/results.xml
          retention-days: 30