name: inspect-build-test

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: zzavidd/blog-zavid
      - name: 'Run TypeScript checks'
        run: bun run tsc:ci
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: zzavidd/blog-zavid
      - name: 'Run unit tests'
        run: bun run test:unit
