name: inspect-build-test

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
      - name: 'Install Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.3
      - name: 'Install dependencies'
        run: bun install --frozen-lockfile
      # - name: 'Prisma generate'
      #   run: bun prisma generate
