name: inspect-build-test

on: push

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/cache@v3
        id: bun-cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}
      - run: bun install --frozen-lockfile
      - run: bun prisma generate
      - run: bun run tsc:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/cache@v3
        id: bun-cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}
      - run: bun install --frozen-lockfile
      - run: bun prisma generate
      - run: bun run build

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/cache@v3
        id: bun-cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}
      - run: bun install --frozen-lockfile
      - run: bun test unit

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/cache@v3
        id: bun-cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}
      - run: bun install --frozen-lockfile
      - run: bunx playwright install --with-deps
      - run: bun run test
