name: link-inspector

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install Node.js"
        uses: actions/setup-node@v3
      - name: "Install pnpm"
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 8.2.0
      - name: "Install dependencies"
        run: pnpm install
        working-directory: ./code
        shell: bash
      - name: "Run crawler"
        run: pnpm run test:prod
        working-directory: ./code