name: Release to Production

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - run: git fetch origin main
      - run: git reset --hard origin/main
      - run: git push -f origin production

  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/zavid
            git checkout production
            git fetch origin production
            git reset --hard origin/production
            docker-compose up -d --build production
